### ISSUE TITLE
Use APA style for citation

### ISSUE THREAD

**Issue by mattberjon** [mattberjon/auditory-motion-perception#2]
The current project uses sphinxcontrib-bibtex to process a bibtex file. The style are quite limited and doesn't include APA style (which is the original style used in the LaTeX thesis). It would be good to be able to integrate the basics of this style for a better reading.

**Comment by pjmark** [comment]
Hi

I was just wondering about the sphinxcontrib-bibtex.  I myself cannot make it work on readthedocs.org but it works for you.  Would you have any idea why?

My citations are read from the bib file (5 of them) but are not recognised.  They work offline when compiled on my machine but not on readthedocs.org. (https://github.com/pjmark/NiftyPET)

If you would have any tips I would greatly appreciate them.

PS I really like your thesis.

**Comment by mattberjon** [comment]
Hi @pjmark,
I had the same issue and it's a [known issue][l1] in sphinxcontrib-bibtex. You must ensure that your file is processed after all citations, that's why my reference file name is appended with the letter z. Give it a shot and it should work.

[l1]: https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#unresolved-citations-across-documents

**Comment by pjmark** [comment]
Matthieu, thank you so much.  I would never have guessed this!

Take care!
________________________________
